spring.application.name=OnlineBookHouse_Books_Service

server.port=9091



# =========================
# EUREKA CLIENT CONFIG
# =========================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

eureka.instance.prefer-ip-address=true


# =========================
# ACTUATOR CONFIG
# =========================
management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

management.info.env.enabled=true

management.endpoint.shutdown.enabled=true


# =========================
# APPLICATION INFO
# =========================
info.app.name=Online Book House Book adding Service
info.app.description=Book Adding Microservice
info.app.version=1.0


# =========================
# LOGGING CONFIG
# =========================
logging.level.root=INFO

logging.level.org.springframework.web=DEBUG

logging.file.name=logs/book-register-service.log


# =========================
# SPRING BOOT ADMIN CLIENT
# =========================
spring.boot.admin.client.url=http://localhost:1111

spring.boot.admin.client.instance.prefer-ip=true


# =========================
# ZIPKIN (OPTIONAL)
# =========================
management.tracing.sampling.probability=1.0


# =========================
# SERVER ERROR CONFIG
# =========================
server.error.include-message=always

server.error.include-binding-errors=always
