spring.application.name=OnlineBookHouse_Config_Server

server.port=8888

application.title=${spring.application.name}

# Enable Git Repository
spring.cloud.config.server.git.uri=https://github.com/satyamk-dev/OnlineBookHouse_Config_Server.git


# Default branch
spring.cloud.config.server.git.default-label=master

# Clone repo on startup
spring.cloud.config.server.git.clone-on-start=true

#Monitor and getting info
management.endpoints.web.exposure.include=*
